swagger: '2.0'
info:
  version: 1.0.0
  title: List of students
  description: |
    API to list of students created for Advanced Objective Programming labs.
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /students:
    get:
      description:  Returns array with all students objects in database
      responses:
        200:
          description:  List all students
          schema:
            title: Students
            type: array
            items:
              $ref: '#/definitions/Student'
  /students/{id}:
    get:
      description:  Returns student object with given id
      parameters:
        - name: id
          in: path
          type: string
          description: ID of the student
          required: true
      responses:
        200:
          description:  One student
          schema:
            title: Student
            type: object
            items:
              $ref: '#/definitions/Student'
  /students{id}:
    post:
      parameters:
      - name: id
        in: path
        type: string
        description: ID of the student
        required: true
      responses:
        200:
          description:  Student has been updated.
    delete:
      parameters:
      - name: id
        in: path
        type: string
        description: ID of the student
        required: true
      responses:
        200:
          description:  Student has been deleted.

definitions:
  Student:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      PESEL:
        type: string
      address:
        type: string
      email:
        type: string
      klasa:
        type: string 